[versions]
compose = "1.2.0-rc02"
kotlin = "1.6.21"

[libraries]
androidx-activity-compose = "androidx.activity:activity-compose:1.3.0"
androidx-core = "androidx.core:core-ktx:1.3.2"
androidx-appcompat = "androidx.appcompat:appcompat:1.2.0"

android-gradlePlugin = "com.android.tools.build:gradle:7.2.1"

compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-ui-core = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }

kotlin-core = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

material = "com.google.android.material:material:1.3.0"

junit = "junit:junit:4.13.2"

[bundles]
compose = ["compose-foundation", "compose-material", "compose-ui-core", "compose-ui-tooling"]
