[versions]
androidGradlePlugin = "7.4.2"
compileSdk = "33"
composeCompiler = "1.4.4"
composeMultiplatform = "1.3.1"
kotlin = "1.8.10"
kotlinCoroutines = "1.6.4"
minSdk = "24"
targetSdk = "33"

[libraries]
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }

androidx-activity-compose = "androidx.activity:activity-compose:1.7.0"
androidx-core = "androidx.core:core-ktx:1.9.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"

kotlin-core = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinCoroutines" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

material = "com.google.android.material:material:1.8.0"

junit = "junit:junit:4.13.2"

[plugins]
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
