[versions]
androidGradlePlugin = "7.4.2"
compileSdk = "33"
composeCompiler = "1.4.4"
composeMultiplatform = "1.4.0-rc03"
kotlin = "1.8.10"
kotlinCoroutines = "1.6.4"
minSdk = "24"
targetSdk = "33"

[libraries]
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }

androidx-activityCompose = { module = "androidx.activity:activity-compose", version = "1.7.0" }

androidx-core = { module = "androidx.core:core-ktx", version = "1.9.0" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }

kotlin-core = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinCoroutines" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

material = { module = "com.google.android.material:material", version = "1.8.0" }

junit = { module = "junit:junit", version = "4.13.2" }

[plugins]
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
